---
abstract: 'Compile SOAP WSDL from your Moose classes.'
author:
  - 'Alex J. G. Burzyński <ajgb@cpan.org>'
build_requires:
  Data::Dumper: 0
  List::Util: 1.21
  Moose: 0.93
  MooseX::Params::Validate: 0.12
  MooseX::Types::XMLSchema: 0.02
  Perl6::Junction: 1.40000
  Test::Differences: 0
  Test::More: 0
  Test::NoWarnings: 0
  XML::LibXML: 1.69
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WSDL-Compile
provides:
  Moose::Meta::Attribute::Custom::WSDL:
    file: lib/WSDL/Compile/Meta/Attribute/WSDL.pm
  WSDL::Compile:
    file: lib/WSDL/Compile.pm
    version: 0.03
  WSDL::Compile::Meta::Attribute::WSDL:
    file: lib/WSDL/Compile/Meta/Attribute/WSDL.pm
    version: 0.02
  WSDL::Compile::Utils:
    file: lib/WSDL/Compile/Utils.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
